
# Build docker image

- name: Log into DockerHub
  docker_login:
    username: "{{ lookup('env','DOCKER_USER') }}"
    password: "{{ lookup('env','DOCKER_PASS') }}"

- name: Move the Dockerfile to the projet root (required for the build context)
  template:
    src: templates/Dockerfile.template
    dest: "../../../Dockerfile"
  vars:
    db_schema: "{{ lookup('env','DB_SCHEMA') }}"
  delegate_to: 127.0.0.1
  become: false

- name: Build docker image
  docker_image:
    build:
      path: ../../..
      dockerfile: ./Dockerfile
      pull: no
    repository: "{{ docker_user }}/{{ docker_user }}_api_app"
    name: "heticmadu_api_app"
    tag: latest
    push: yes
    source: build
    force_source: yes
    force_tag: yes
  delegate_to: 127.0.0.1
  become: false