sudo: required

services:
  - docker

language: node_js

node_js:
  - node

branches:
  only:
    - master
    - deployment

env:
  global:
    - ENCRYPTED_PRIVATE_KEY_PATH=./devops/private_key.enc
    - PRIVATE_KEY_PATH=./private_key

script:
  - npm i
  - npm run build
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USERNAME/heticmadu-api-app:latest -f ./devops/docker/Dockerfile ./
  - docker push $DOCKER_USERNAME/heticmadu-api-app:latest
  - ls
  - ls ./devops
  - openssl aes-256-cbc -K $encrypted_584f93c26d12_key -iv $encrypted_584f93c26d12_iv -in ./devops/private_key.enc -out ./private_key -d
  - openssl aes-256-cbc -K $encrypted_584f93c26d12_key -iv $encrypted_584f93c26d12_iv -in ./.env.enc -out ./.env -d
  - ssh-keyscan -H $EC2_URL
  - chmod -R 600 $PRIVATE_KEY_PATH
  - eval $(ssh-agent)
  - ssh-add $PRIVATE_KEY_PATH
  - scp -o StrictHostKeyChecking=no ./devops/docker/docker-compose.yml ubuntu@$EC2_URL:/home/ubuntu/docker-compose.api.yml
  - scp -o StrictHostKeyChecking=no ./.env ubuntu@$EC2_URL:/home/ubuntu/.env
  - ssh -i $PRIVATE_KEY_PATH ubuntu@$EC2_URL 'bash -s' < ./devops/deploy.sh
  - rm $PRIVATE_KEY_PATH