sudo: required

services:
  - docker

language: node_js

node_js:
  - node

branches:
  only:
    - master
    - deployment

env:
  global:
    - DEVOPS_DIR=./devops/prod
    - ANSIBLE_TEMPLATES_DIR=$DEVOPS_DIR/ansible/roles/api/templates

script:
# extract secrets
  - openssl aes-256-cbc -K $encrypted_584f93c26d12_key -iv $encrypted_584f93c26d12_iv -in $DEVOPS_DIR/secrets/secrets.tar.enc -out secrets.tar -d
  - tar xvf ./secrets.tar

# install dependencies
  - npm i typeorm ts-node mysql
  - sudo apt-get install python3 python3-pip
  - pip3 install docker-py setuptools
  - pip3 install ansible

# configure ssh
  - chmod -R 600 $DEVOPS_DIR/secrets/private_key
  - eval $(ssh-agent)
  - ssh-add $DEVOPS_DIR/secrets/private_key

# configure ansible
  - export BOTO_USE_ENDPOINT_HEURISTICS=true

# run ansible playbook
  - ansible-playbook $DEVOPS_DIR/ansible/main.yml --user ubuntu -i $DEVOPS_DIR/ansible/inventory/ec2.py
