---

# Fetch db info

- name: get rds info
  rds_instance_info:
    db_instance_identifier: heticmadu-prod
    region: eu-west-3
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: rds_info

# Add variables to templates that will be used locally

- name: Add variables to local migration config file
  template:
    src: templates/ormconfig.js.template
    dest: "../db/ormconfig.js"
  vars:
    db_host: "{{ rds_info.instances[0].endpoint.address }}"
    db_port: "{{ lookup('env','DB_PORT') }}"
    db_schema: "{{ lookup('env','DB_SCHEMA') }}"
    db_user: "{{ lookup('env','DB_USER') }}"
    db_pass: "{{ lookup('env','DB_PASS') }}"
  delegate_to: 127.0.0.1
  become: false

- name: Add variables to local .env file
  template:
    src: templates/.env.template
    dest: "../secrets/.env"
  vars:
    db_host: "{{ rds_info.instances[0].endpoint.address }}"
    db_port: "{{ lookup('env','DB_PORT') }}"
    db_schema: "{{ lookup('env','DB_SCHEMA') }}"
    db_user: "{{ lookup('env','DB_USER') }}"
    db_pass: "{{ lookup('env','DB_PASS') }}"
    jwt_secret: "{{ lookup('env','JWT_SECRET') }}"
  delegate_to: 127.0.0.1
  become: false

# Build docker image

- name: Log into DockerHub
  docker_login:
    username: "{{ lookup('env','DOCKER_USER') }}"
    password: "{{ lookup('env','DOCKER_PASS') }}"

- name: Move the Dockerfile to the projet root (required for the build context)
  template:
    src: templates/Dockerfile.template
    dest: "../db/Dockerfile"
  vars:
    db_schema: "{{ lookup('env','DB_SCHEMA') }}"
  delegate_to: 127.0.0.1
  become: false

- name: Build docker image
  docker_image:
    build:
      path: ../../..
      dockerfile: ./devops/prod/db/Dockerfile
      pull: no
    repository: "{{ docker_user }}"
    name: "heticmadu_api_app"
    tag: latest
    push: no
    source: build
  delegate_to: 127.0.0.1
  become: false

- name: Push docker image
  docker_image:
    repository: "{{ docker_user }}"
    name: "heticmadu_api_app"
    tag: latest
    source: local
    push: yes
  delegate_to: 127.0.0.1
  become: false

# Prepare environment

- name: Create directory structure
  file:
    path: "{{ app_directory }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Upload .env file
  template:
    src: templates/.env.template
    dest: "{{ app_directory }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  vars:
    db_host: "{{ rds_info.instances[0].endpoint.address }}"

- name: Upload docker-compose file
  template:
    src: templates/docker-compose.yml.template
    dest: "{{ app_directory }}/docker-compose.yml"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

# Restore db (from localhost)

# TODO: perform a backup

- name: Apply migration script
  shell:
    chdir: ../../..
    cmd: ./devops/prod/scripts/apply_db_migration.sh
  delegate_to: 127.0.0.1
  become: false

# Launch app

- name: Start docker-compose
  docker_compose:
    project_src: "{{ app_directory }}"
    restarted: yes
    remove_orphans: yes
